### ISSUE TITLE
new suggestion to ignore commented lines 

### ISSUE THREAD

**Issue by ravindra1985** [wardi/jsonlines#43]
What do you think about commented lines for better readability of the file 

[hash] Person records
{"label": "Person", "id":"001"}
{"label": "Person", "id":"002"}
[hash] Employee records
{"label": "Employee", "id":"001"}
{"label": "Employee", "id":"002"}

**Comment by wardi** [comment]
I'm against a special comment syntax because:
1. `# comment` is invalid JSON so parsing becomes more complicated
2. comments make using unix text processing commands like `head`, `tail`, `grep` etc. more complicated by breaking the text lines <-> record number mapping i.e. record 1 is on line 1, record 2 is on line 2…

**Comment by mcast** [comment]
(it's a duplicate of #23)
